### ISSUE TITLE
Check with contextual tuple exhibits non-deterministic behavior while running openfga with query cache enabled 

### ISSUE THREAD

**Issue by padhikari-godaddy** [openfga/openfga#1058]
**Summary**

Check with contextual tuple exhibits non-deterministic behavior while running openfga with query cache enabled 

- Steps to reproduce
   - Run openfga with check query cache enabled
      `./openfga run  --experimentals check-query-cache --check-query-cache-enabled=true`
   -  Use the model and tuples provided from the Store data section below.
   - Run those three checks in order.

- What did you expect to happen?
    - The `check-1` request should respond with `allowed`: `true`
    - The `check-2` request should respond with `allowed`: `false`
    - The `check-3` request should respond with `allowed`: `true`

- What actually happened?
    - The `check-1` request should respond with `allowed`: `true`
    - The `check-2` request should respond with `allowed`: `false`
    - The `check-3` request should respond with `allowed`: `false`
   If you wait for some time (basically for the cache to expire) and make `check-3` request again, it responds with  `allowed`: `true`.

**OpenFGA version or commit**

Issue exists in the `2b04c251e5f99ccd5bd39eb0485f987deaa9f9ef` or v1.3.3 release.

**Store data**

If applicable, provide information about your authorization model, tuples, and the Check or ListObjects calls you're making. For example:

```yaml
model_file: |
  model
  schema 1.1
type fga_user
type timeslot
  relations
    define user: [fga_user]
type commerce_store
  relations
    define approved_hourly_access: user from approved_timeslot and hourly_employee
    define approved_timeslot: [timeslot]
    define hourly_employee: [fga_user]

tuples:
  - user: fga_user:anne
    relation: hourly_employee
    object: commerce_store:0
  - user: fga_user:anne
    relation: hourly_employee
    object: commerce_store:1
  - user: timeslot:11_12
    relation: approved_timeslot
    object: commerce_store:0
   - user: timeslot:12_13
    relation: approved_timeslot
    object: commerce_store:1
tests: # remove this if not a bug in Check or ListObjects API
  - name: check-1
    check:
      {
        "tuple_key": {
          "user": "fga_user:anne",
          "relation": "approved_hourly_access",
          "object": "commerce_store:0"
        },
        "contextual_tuples": {
          "tuple_keys": [
            {
              "user": "fga_user:anne",
              "relation": "user",
              "object": "timeslot:11_12"
            }
          ]
        }
      }
 - name: check-2
    check:
      {
        "tuple_key": {
          "user": "fga_user:anne",
          "relation": "approved_hourly_access",
          "object": "commerce_store:1"
        },
        "contextual_tuples": {
          "tuple_keys": [
            {
              "user": "fga_user:anne",
              "relation": "user",
              "object": "timeslot:11_12"
            }
          ]
        }
      }
- name: check-3
   check:
      {
        "tuple_key": {
          "user": "fga_user:anne",
          "relation": "approved_hourly_access",
          "object": "commerce_store:1"
        },
        "contextual_tuples": {
          "tuple_keys": [
            {
              "user": "fga_user:anne",
              "relation": "user",
              "object": "timeslot:12_13"
            }
          ]
        }
      }

   
```

**Other data**

- How are you running OpenFGA? (As a binary, in Docker, in Kubernetes)
    - Building from source with go build](https://github.com/openfga/openfga#building-from-source-with-go-build)
- What datastore are you using? (In memory, MySQL, Postgres)
   - In memory
- Are you running OpenFGA with any configuration overrides or with any of the flags mentioned in `./openfga run --help`?
   -    `./openfga run  --experimentals check-query-cache --check-query-cache-enabled=true`
- Do you have any logs or traces that could help us debug the problem?
Server logs below:
> 
```2023-10-10T15:44:36.252-0700    INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "11eb37a9-713a-4e3f-b128-13a96f88cc0f", "user_agent": "Thunder Client (https://www.thunderclient.com)", "raw_request": {"store_id":"01HC34M687XEFK4E0VGGZ3KTY8","tuple_key":{"object":"commerce_store:0","relation":"approved_hourly_access","user":"fga_user:anne"},"contextual_tuples":{"tuple_keys":[{"object":"timeslot:11_12","relation":"user","user":"fga_user:anne"}]},"authorization_model_id":"","trace":false}, "raw_response": {"allowed":true,"resolution":""}, "peer.address": "127.0.0.1:58363", "store_id": "01HC34M687XEFK4E0VGGZ3KTY8", "authorization_model_id": "01HCBEKQHWDHAHZV5FE9F1HB0D", "datastore_query_count": 3, "grpc_code": 0}```

>
```2023-10-10T15:44:42.699-0700    INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "a08f488a-44b8-4abb-b05c-5ba22fe1263b", "user_agent": "Thunder Client (https://www.thunderclient.com)", "raw_request": {"store_id":"01HC34M687XEFK4E0VGGZ3KTY8","tuple_key":{"object":"commerce_store:1","relation":"approved_hourly_access","user":"fga_user:anne"},"contextual_tuples":{"tuple_keys":[{"object":"timeslot:11_12","relation":"user","user":"fga_user:anne"}]},"authorization_model_id":"","trace":false}, "raw_response": {"allowed":false,"resolution":""}, "peer.address": "127.0.0.1:58363", "store_id": "01HC34M687XEFK4E0VGGZ3KTY8", "authorization_model_id": "01HCBEKQHWDHAHZV5FE9F1HB0D", "datastore_query_count": 3, "grpc_code": 0}```

>
```2023-10-10T15:44:50.236-0700    INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "70eb9be6-2de0-4b70-acfb-6eb43e93d5d6", "user_agent": "Thunder Client (https://www.thunderclient.com)", "raw_request": {"store_id":"01HC34M687XEFK4E0VGGZ3KTY8","tuple_key":{"object":"commerce_store:1","relation":"approved_hourly_access","user":"fga_user:anne"},"contextual_tuples":{"tuple_keys":[{"object":"timeslot:12_13","relation":"user","user":"fga_user:anne"}]},"authorization_model_id":"","trace":false}, "raw_response": {"allowed":false,"resolution":""}, "store_id": "01HC34M687XEFK4E0VGGZ3KTY8", "authorization_model_id": "01HCBEKQHWDHAHZV5FE9F1HB0D", "datastore_query_count": 1, "peer.address": "127.0.0.1:58363", "grpc_code": 0}```
>
```2023-10-10T15:45:07.178-0700    INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "5f5c66e8-199f-4f69-941e-6f1d1c0401a3", "user_agent": "Thunder Client (https://www.thunderclient.com)", "raw_request": {"store_id":"01HC34M687XEFK4E0VGGZ3KTY8","tuple_key":{"object":"commerce_store:1","relation":"approved_hourly_access","user":"fga_user:anne"},"contextual_tuples":{"tuple_keys":[{"object":"timeslot:12_13","relation":"user","user":"fga_user:anne"}]},"authorization_model_id":"","trace":false}, "raw_response": {"allowed":true,"resolution":""}, "store_id": "01HC34M687XEFK4E0VGGZ3KTY8", "authorization_model_id": "01HCBEKQHWDHAHZV5FE9F1HB0D", "datastore_query_count": 3, "peer.address": "127.0.0.1:58363", "grpc_code": 0}```
