### ISSUE TITLE
Performance degradation with increasing tuple count

### ISSUE THREAD

**Issue by aaronschweig** [openfga/openfga#1154]
**Summary**

Hello everybody 👋 

### Actual Behaviour

While trying out OpenFGA for our use case I noticed some interesting behaviour which seems pretty odd to me. You can see our model below. We want to achieve an open by default role based model within OpenFGA which does not need model changes to define new roles and assignments for users. We came up with our model as a first working prototype and started to fill up the model with some tuples. We chose postgres as our storage system.

After inserting the first few tuples (for one or two users) which can also be extraced from below, we ran the first `Check` calls which as for the allowance of `tenant:a#project_c@user:anne`, which correctly evaluated to true. As we deployed it with the help of the official helm chart we also enabled tracing to get some performance insights and see how our model behaves. Initially openfga reported that it performed roughly around ~40 traced operations, which correlated to around 6 reads to the database according to the trace. It also gave an ok performance of 43.42ms.

<details>
<summary>OpenFGA traces for 40ms check</summary>

[trace.json](https://github.com/openfga/openfga/files/13366257/trace.json)

</details>

This seemed okay for our use case so we continued to gradually fill up the graph with tuples to try out it out within our dev environment and see if the integration is working. We ended up with filling in the same three tuples for every user that is part of the organization and look at how the model performs again.

```yaml
tuples:
- user: user:anne
  relation: user
  object: rb:anne-tenant_a
- user: role:tenant-employee
  relation: role
  object: rb:anne-tenant_a
- user: rb:anne-tenant_a
  relation: granted
  object: tenant:a
```

After writing a very small amount of users and tuples of around 35 users (which would correlate to 105 tuples) we looked again in the tracing to gather more information about timing and performance implications for our system. Then we noticed, something off. The time for each `Check` request increased to way over 100ms per check request and ~500 traces reported per request. We also saw that the amount of database requests increased to 65 per `Check` request, which seems quite a lot considering the relatively small amount of tuples inside openfga.

<details>
<summary>OpenFGA traces for >100ms check</summary>

[trace_100.json](https://github.com/openfga/openfga/files/13366260/trace_100.json)

</details>

### Expected behaviour

We expected to have a similiar performance with an increasing amount of tuples as we have a few thousand users that need to be inserted into that model which is also very much stripped down as there should also be a few more types defined in the future. It would be great to give some insights on how its maybe the fault of the model or of some of the other components involved that can cause such a rapid degradation of the openfga performance since we thought it would be able to handle a way higher amount of tuples than this without too much negative impact on the system.

How are we running openfga?

We are using the official helm chart to deploy it into our kubernetes cluster. The openfga deployment is available in 3 replicatas and connects to a CloudSQL postgres Database provided by GCP. The CloudSQL database is running postgres 15 and has 4 CPUS as well as 16GB of memory and uses an SSD as storage. We also balanced the max concurrent database connection according to the [Running in production](https://openfga.dev/docs/getting-started/running-in-production) recommendation.

The provided examples are just randomly picked in case its needed for debugging or investigation purposes. I can also provide examples where openfga reports ~900 spans for one `Check` call. We also had a look into https://github.com/openfga/openfga/issues/727 to see if there are some more insights on what we could be doing wrong or why the performance is not as expected.

**OpenFGA version or commit**

We are running the latest version of the helm chart together with the latest released version of openfga which is as of now 1.3.7.

**Store data**

If applicable, provide information about your authorization model, tuples, and the Check or ListObjects calls you're making. For example:

```yaml
model_file: |
  model
    schema 1.1

  type user

  type role
    relations
      define project_c: [user:*]
      define project_r:  [user:*]

  type rb
    relations
      define user: [user]
      define role: [role]
  
      define project_c: user and project_c from role
      define project_r: user and project_r from role
  
  type tenant
    relations
      define granted: [rb]

      define project_c: project_c from granted
      define project_r: project_r from granted

tuples:
  - object: role:tenant-employee
    relation: project_c
    user: user:*
  - user: user:anne
    relation: user
    object: rb:anne-tenant_a
  - user: role:tenant-employee
    relation: role
    object: rb:anne-tenant_a
  - user: rb:anne-tenant_a
    relation: granted
    object: tenant:a
```

I would really appreciate any help/input to this topic! Thank you already and let me know in case anything else on information is needed!

**Comment by miparnisari** [comment]
Hi @aaronschweig! I inspected the second trace you shared. It looks like the number of tuples was irrelevant in that case, what happened was that the path in the graph that led to `allowed=true` happened to have an (unfortunate) slow database read:

<img width="1919" alt="image" src="https://github.com/openfga/openfga/assets/5374887/d4052fb2-1b26-4182-8bcc-ff0c979c2635">

Could you share all the options that you've configured the OpenFGA instances with? Also, I'm not familiar with GCP but I'm wondering if there is something that can be tweaked on that front. Do you have metrics in GCP regarding latency of database reads?

**Comment by aaronschweig** [comment]
Hey @miparnisari thanks for investigating and giving some first feedback! I have collected the information about our database in GCP and also the deployment configuration of openfga:

Here are the contents of the `values.yaml`:

```yaml
log:
  level: info
autoscaling:
  enabled: false
  
telemetry:
  trace:
    enabled: true
    otlp:
      endpoint: otlp-gateway-collector.dxp-system.svc.cluster.local:4317
    sampleRatio: 1.0

replicaCount: 3
migrate:
  annotations:
    sidecar.istio.io/inject: "false"
datastore:
  engine: postgres
  uriSecret: openfga-db
  maxOpenConns: 30
  applyMigrations: true
```

which result in the following env vars on the deployment

```yaml
env:
  - name: OPENFGA_DATASTORE_ENGINE
    value: postgres
  - name: OPENFGA_DATASTORE_URI
    valueFrom:
      secretKeyRef:
        key: uri
        name: openfga-db
  - name: OPENFGA_DATASTORE_MAX_OPEN_CONNS
    value: "30"
  - name: OPENFGA_GRPC_ADDR
    value: 0.0.0.0:8081
  - name: OPENFGA_HTTP_ENABLED
    value: "true"
  - name: OPENFGA_HTTP_ADDR
    value: 0.0.0.0:8080
  - name: OPENFGA_HTTP_CORS_ALLOWED_ORIGINS
    value: '*'
  - name: OPENFGA_HTTP_CORS_ALLOWED_HEADERS
    value: '*'
  - name: OPENFGA_PLAYGROUND_ENABLED
    value: "true"
  - name: OPENFGA_PLAYGROUND_PORT
    value: "3000"
  - name: OPENFGA_LOG_FORMAT
    value: json
  - name: OPENFGA_LOG_LEVEL
    value: info
  - name: OPENFGA_REQUEST_DURATION_DATASTORE_QUERY_COUNT_BUCKETS
    value: 50,200
  - name: OPENFGA_METRICS_ENABLED
    value: "true"
  - name: OPENFGA_METRICS_ADDR
    value: 0.0.0.0:2112
  - name: OPENFGA_TRACE_ENABLED
    value: "true"
  - name: OPENFGA_TRACE_OTLP_ENDPOINT
    value: otlp-gateway-collector.dxp-system.svc.cluster.local:4317
  - name: OPENFGA_TRACE_SAMPLE_RATIO
    value: "1"
```

As for some metrics about our database with regards to latency etc I searched a bit and could offer some insights like that:

![image](https://github.com/openfga/openfga/assets/42006873/7a3e1b7a-8521-49ec-8f2e-1082bb727d15)
![image](https://github.com/openfga/openfga/assets/42006873/50585b02-59b9-468c-bf5a-660a4f5932a3)

So as you can see the average query execution time and resource consumption is fine FMPOV. If you need some other metrics just let me know - happy to see what I can find 😃

**Comment by miparnisari** [comment]
@aaronschweig those metrics look good 👍 do you have any metrics on the networking between the OpenFGA replicas and the database? Are they deployed in the same datacenter?

**Comment by aaronschweig** [comment]
> Hi @aaronschweig
> 
> I saw you are trying to build an 'We want to achieve an open by default role based model within OpenFGA which does not need model changes to define new roles and assignments for users', can you elaborate on that? I have a hard time understanding what you want to achieve with the model above.

Well if the model is that bad 😋 No thanks for reaching out! Let me try to clarify verbally what was tried of being achieved with this model and maybe you can also give feedback if we did it right or if it was constructed wrongly.

To give a little bit of context: I've cut a few other types away from the model as we did not fill them yet and to keep it simple for the purpose of investigating what causes our issue. We are building an internal developer portal which by design should allow every member of the company to be able to "read" any project within the company. We also have more than one tenant and a 1:n relationship between a tenant and projects.

We also wanted to achieve the goal of being able to modify the permissions this model can grant without the need of modifying relations in the model itself - this is why we chose to go with the concept of roles (of course the role type needs the relations to store concrete permissions like "can create a project", "can read project" and many more in the future) and rolebindings, which allow us to attach a role to either level of the hierarchy in the end - so we can grant permissions either on tenant level, project level and so one with a few levels below. This would, at least in our heads, allow us to simultaneously grant permissions (like reading projects) on tenant level rather than storing it for each user in every project, and also give more fine grained permissions or end-user customised roles on various entities in the entire system. It was also planned to store some technical permission within the same model, e.g. if a service A is allowed to perform a certain action on an entity in the model. This would allow us to cover a lot of use cases and problems with one solution rather than trying to streamline a lot of solutions for all the individual problems.

This is also why we went with `user:*` to achieve this "allow by default" behaviour for reading and creating projects as every user in the systems (with some exceptions covered by a different role) should be able to perform this actions. So on login of a user we make sure this 

```yaml
 - user: user:anne
    relation: user
    object: rb:anne-tenant_a
  - user: role:tenant-employee
    relation: role
    object: rb:anne-tenant_a
  - user: rb:anne-tenant_a
    relation: granted
    object: tenant:a
 ```

tuple set is granted on tenant level so the user is able to read projects and also to create projects.

We also saw within the documentation and the more advanced examples that our approach doesn't seem to be very popular in not storing the concrete permissions as relations and we also had struggle figuring out how to achieve this "allow reading for everybody" approach could be properly realised. 

I hope I could shed some light onto our idea and already thank you so much for jumping in and taking care of our (probably self-injected) problems! I am very happy for some feedback to the model and if we have the right mental model for what we want to achieve with openfga!
