### ISSUE TITLE
Check gives two responses at random if one of the branches of evaluation errors

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1238]
**Summary**

Check gives two responses, depending on which branch of the `but not` gets evaluated first:
- allowed=false, or
- "failed to evaluate relationship condition: 'condX' - context is missing parameters '[x]'"

**OpenFGA version or commit**

1.4.0

**Store data**

```yaml
model_file: |
model
  schema 1.1
type user
type document
  relations
    define admin: [user:*]
    define viewer: [user with condX] but not admin
condition condX(x: int) {
   x > 100
}
tuples:
  - user: user:*
    relation: admin
    object: document:budget
  - user: user:maria
    relation: viewer
    object: document:budget
    condition: 
      name: condX
tests:
  - name: test-1
    check:
      - user: user:maria
        object: document:budget
        assertions:
          viewer: false
    list_objects:
      - user: user:maria
        type: document
        assertions:
          viewer:
```
