### ISSUE TITLE
GoRoutine leak for list objects when there are more than 1000 items to return

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1296]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Discord](https://discord.gg/8naAwJfWN6) community and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

PProf shows that there are goroutine leaks in ListObjects when the number of items > max items for list objects

### Expectation

No goroutine leaks

### Reproduction

1. Set profiler enabled by specifying `--profiler-enabled`.  It does not matter what the datastore is
2. Create new model 
```
model
  schema 1.1

type user

type group
  relations
    define member: [user]
```
3. Adding tuples `group:1#member@user:A` to `group:10000#member@user:A`
4. Call list objects with `group#member@user:A`
5. Inspect profiler http://localhost:3001/debug/pprof/goroutine?debug=1 .  See that the number of goroutine increases per list object call.

### Store data

```yaml
model_file: |
model
  schema 1.1

type user

type group
  relations
    define member: [user]

tuples:
  - user: user:A
    relation: member
    object: group:1
...
  - user: user:A
    relation: member
    object: group:10000
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    list_objects:
      - user: user:A
        type: group
        relation: member
```

### OpenFGA version

1.4.1

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

--profiler-enabled
