### ISSUE TITLE
Suboptimal performance if model ID is not specified in Check and ListObjects APIs

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1386]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Discord](https://discord.gg/8naAwJfWN6) community and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When auth model ID is not specified, it requires 2 DB lookup instead of 1 to fetch the latest.

Split from https://github.com/openfga/openfga/issues/1289

### Expectation

1 DB lookup should be sufficient to fetch the latest model.

### Reproduction

Call Check API and not specified auth model ID, you will observe that two DB lookups are needed in typesystem resolver

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type organization
    relations
      define member: [user]
tuples:
  - user: user:anne
    relation: member
    object: organization:openfga
  - user: user:bob
    relation: member
    object: organization:openfga
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    check:
      - user: user:anne
        object: organization:openfga
        assertions:
          member: true
    list_objects:
      - user: user:anne
        type: organization
        assertions:
          member:
            - organization:openfga
```

### OpenFGA version

1.4.3

### How are you running OpenFGA?

As a binary

### What datastore are you using?

MySQL

### OpenFGA Flags

N/A
