### ISSUE TITLE
HandleTupleValidateError throw 500 errors when condition is invalid 

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1419]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

OpenFGA server throws "Internal Server Error" when condition is invalid

### Expectation

Should throw HTTP 400 error instead

### Reproduction

1. Run check with the model / data below and see 500 error thrown with the following error message

### Store data

```yaml
model_file: |
model
  schema 1.1

type user

type group
  relations
    define member: [user]
    define can_access: [user with less_than_hundred]
    
condition less_than_hundred(x: int) {
  x < 100
}


tuples:
  - user: user:test
    relation: can_access
    object: group:8
    context:
       "x": "b"

```

### OpenFGA version

1.5.0

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

N/A

### Logs

2024-03-04T14:38:41.639-0500	ERROR	rpc error: code = Code(4000) desc = Internal Server Error	{"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "6e1745c8-eb89-47db-8b1c-ae11c1aec3e9", "user_agent": "PostmanRuntime/7.36.3", "raw_request": {"store_id":"01HR5EK73WXEHTHPJKV7PSCK0W","tuple_key":{"user":"user:test","relation":"can_access","object":"group:8"},"contextual_tuples":{"tuple_keys":[{"user":"user:test","relation":"can_access","object":"group:8","condition":{"name":"less_than_hundred","context":{"x":"b"}}}]},"authorization_model_id":"","trace":false,"context":null}, "raw_response": {"code":"internal_error","message":"Internal Server Error"}, "peer.address": "127.0.0.1:61663", "store_id": "01HR5EK73WXEHTHPJKV7PSCK0W", "authorization_model_id": "01HR5ESB7EK9ZCSTCT2TNZ86T8", "grpc_code": 4000, "internal_error": "Invalid tuple 'group:8#can_access@user:test (condition name:\"less_than_hundred\" context:{fields:{key:\"x\" value:{string_value:\"b\"}}})'. Reason: parameter type error on condition 'less_than_hundred' - failed to convert context parameter 'x': expected a int64 value, but found invalid string value 'b'"}
