### ISSUE TITLE
openfga does not start as helm child

### ISSUE THREAD

**Issue by lachnerd** [openfga/openfga#1472]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

openfga does not start if deployed on azure aks as helm child chart using postgres database engine.
the pod says:
````bash
Back-off restarting failed container wait-for-migration in pod
```

I also see no job that does the migration i think that might be the problem.

I tested locally with docker-dekstop-k8s everything works as expected:
- postgres starts
- migrate job does whatever this migarte job does
- openfg starts successfulley

Any clues or hints for me?




### Expectation

openfga starts with postgres backend

### Reproduction

integrate as child dependency
add some yaml
select postgres

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type organization
    relations
      define member: [user]
tuples:
  - user: user:anne
    relation: member
    object: organization:openfga
  - user: user:bob
    relation: member
    object: organization:openfga
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    check:
      - user: user:anne
        object: organization:openfga
        assertions:
          member: true
    list_objects:
      - user: user:anne
        type: organization
        assertions:
          member:
            - organization:openfga
```


### OpenFGA version

1.40

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

Postgres

### OpenFGA Flags

waitForMigrations: true

### Logs

_No response_
