### ISSUE TITLE
OpenFGA Migrate Job Fails with Unescaped URI

### ISSUE THREAD

**Issue by joshmorningstar** [openfga/openfga#1509]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When trying to deploy OpenFGA with Postgres via Kubernetes we ran into a “userinfo” parsing error. We are providing the Job the credentials via external secrets as outlined in the helm template conditional. The final manifest produces the following URI (redacted to remove all production references): `”uri”: “postgres://postgres:<password-containing-unescaped-characters>@host:port/database”`. The password contains hyphens, curly brackets, and parenthesis; looking into url.parse() in Golang it looks like it is expecting escaped characters. 

```
case "postgres":
		driver = "pgx"
		migrationsPath = assets.PostgresMigrationDir

		// Parse the database uri with url.Parse() and update username/password, if set via flags
		dbURI, err := url.Parse(uri)
```

### Expectation

I would expect this to sanitize the URI string on the backend and not expect the URI to be escaped. For instance, the following URI should be valid:

`postgres://postgres:JdnKsnd83$;):”-&:jaj]^]*}hsnsl@example.com:5432/postgres`

Due to the way `url.parse()` currently handles this, this string would fail due to unescaped non-alpha-numeric characters being present in the password.

### Reproduction

1. Configure OpenFGA in Kubernetes
1. Configure OpenFGA to use Postgres
1. Configure Postgres to use a URI
1. Configure the Postgres URI to contain unescaped non-alpha-numeric characters

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type organization
    relations
      define member: [user]
tuples:
  - user: user:anne
    relation: member
    object: organization:openfga
  - user: user:bob
    relation: member
    object: organization:openfga
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    check:
      - user: user:anne
        object: organization:openfga
        assertions:
          member: true
    list_objects:
      - user: user:anne
        type: organization
        assertions:
          member:
            - organization:openfga
```

# This is not our store data.

### OpenFGA version

v1.5.1

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

Postgres

### OpenFGA Flags

None
