### ISSUE TITLE
Optimising high dispatch and db query counts in broad model

### ISSUE THREAD

**Issue by KlausVii** [openfga/openfga#1607]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

We are experiencing high latency and failing Check queries in production using the auth model below. The problem seems to stem from a particular set of users who have relations with multiple tenants and projects. When a check is performed with one of these users as the object, we are seeing dispatch counts in the hundreds and db query counts over a 100. 

This is causing queries to timeout and putting undue pressure on the db.

Is there anything we could do to make the model perform better while still maintaining the same intent of the model. For example I am aware we could substitute `owner_tenant` and `owner_project` with something like `[tenant#can_view_users]`, but I am not sure if that would reduce the query complexity. 

Another option I am aware of is decreasing the `OPENFGA_RESOLVE_NODE_BREADTH_LIMIT`, but I'm afraid that will lead to an unacceptable number of false negatives.

Any ideas would be appreciated?

### Expectation

I'd expect to be able check relations in a timely manner even for objects that have many relations.

### Reproduction

1. Use the model below.
2. Create a user[0] with many `owner_tenant` and `owner_project` relations
3. Create another user[1] with one shared tenant
4. Check `user[1] can_view user[0]`
5. Observe high dispatch and db query counts 

### Store data

```yaml
model
  schema 1.1

type project
  relations
    define admin: [user] or owner
    define can_view: viewer
    define can_view_users: viewer
    define editor: [user] or admin
    define member: [user] or viewer
    define owner: [user] or super_admin from owner_tenant
    define owner_tenant: [tenant]
    define revoked: [user] or revoked from owner_tenant
    define viewer: [user] or editor

type tenant
  relations
    define admin: [user] or super_admin
    define can_view: (member or external_member) but not revoked
    define can_view_users: member but not revoked
    define editor: [user] or admin
    define external_member: [user]
    define member: [user] or editor
    define revoked: [user]
    define super_admin: [user]

type user
  relations
    define can_edit: owner
    define can_list_memberships: owner
    define can_view: owner or can_view_users from owner_tenant or can_view_users from owner_project
    define owner: [user]
    define owner_project: [project]
    define owner_tenant: [tenant]
```

### OpenFGA version

1.5.3

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

Postgres

### OpenFGA Flags

OPENFGA_CHECK_QUERY_CACHE_ENABLED, OPENFGA_CHECK_QUERY_CACHE_TTL=30s, OPENFGA_DATASTORE_MAX_OPEN_CONNS=500, OPENFGA_MAX_CONCURRENT_READS_FOR_CHECK=4000000, OPENFGA_MAX_CONCURRENT_READS_FOR_LIST_OBJECTS=4000000

### Logs

```
{
	"content": {
		"timestamp": "2024-05-07T09:05:15.952Z",
		"service": "openfga",
		"message": "grpc_req_complete",
		"attributes": {
			"store_id": "01HAM89A85W7HT9MS4KTBN4NPT",
			"raw_request": {
				"store_id": "01HAM89A85W7HT9MS4KTBN4NPT",
				"trace": false,
				"tuple_key": {
					"user": "user:c03fbcc5-5fd8-4711-9be6-33ae29384606",
					"relation": "can_view",
					"object": "user:2d65e2c0-5a9a-47b6-bb8c-236d76f50fdb"
				},
				"authorization_model_id": "01HQ8AZT8BPM228F1E0F5258Y2"
			},
			"level": "info",
			"grpc_service": "openfga.v1.OpenFGAService",
			"datastore_query_count": 515,
			"grpc_code": 0,
			"grpc_method": "Check",
			"grpc_type": "unary",
			"build": {
				"commit": "ebf39989ec19c8c3d8a7646e308bcffca5748874",
				"version": "v1.5.3"
			},
			"peer": {
				"address": "127.0.0.1:37840"
			},
			"dispatch_count": 658,
			"timestamp_milli": "1715072715952",
			"raw_response": {
				"allowed": false,
				"resolution": ""
			},
			"request_id": "629dbfe5-17af-4be2-a9cd-5004be4947eb",
			"user_agent": "openfga-sdk js/0.3.5",
			"timestamp": 1715072715.9523919,
			"authorization_model_id": "01HQ8AZT8BPM228F1E0F5258Y2"
		}
	}
}
```
