### ISSUE TITLE
OpenFGA `migrate` fails to start using k8s on GCP

### ISSUE THREAD

**Issue by gr-bump** [openfga/openfga#1625]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Using k8s on the GCP platform, I'm trying to set up an API container with an OpenFGA container.
Before starting these containers, I initialize a first OpenFGA container (as k8s `initContainers`) to run the `migrate` command.

When I run `kubectl apply`, I get this error when the OpenFga migrate container tries to start:

`failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "migrate": executable file not found in $PATH: unknown`

### Expectation

Container should deploy and start up correctly.

### Reproduction

Here is my k8s yaml file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  xxx-authorization-manager-deployment
  labels:
    app: xxx-authorization-manager
    tags.datadoghq.com/service: "xxx-authorization-manager"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-authorization-manager
  template:
    metadata:
      labels:
        app: xxx-authorization-manager
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: "xxx-authorization-manager"
    spec:
      initContainers:
        - name: openfga-migrate
          image: openfga/openfga:latest
          command: [ "migrate" ]
          envFrom:
            - configMapRef:
                name: xxx-authorization-manager-from-env-map
            - secretRef:
                name: xxx-authorization-manager
      containers:
        - name: xxx-authorization-manager-container
          image: europe-west1-docker.pkg.dev/xxx-dev-350111/xxx/xxx-authorization-manager:1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: xxx-authorization-manager-from-env-map 
            - secretRef:
                name: xxx-authorization-manager
          resources:
            requests:
              cpu: "50m"
              
        - name: openfga
          image: openfga/openfga:latest
          command: [ "run",
                     "--metrics-enabled",
                     "--datastore-metrics-enabled",
                     "--trace-enabled",
                     "--trace-sample-ratio=0.3"
          ]
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: xxx-authorization-manager-from-env-map
            - secretRef:
                name: xxx-authorization-manager
          ports:
            - containerPort: 8080
            - containerPort: 8081
```

### OpenFGA version

1.5.3

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

Postgres

### OpenFGA Flags

No Response
