### ISSUE TITLE
Difference in output when tests fails or succeeds when running fga model test with --verbose flag.

### ISSUE THREAD

**Issue by magnusart** [openfga/openfga#1632]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When I run the command `fga model test --test=..` I get the output:
```
# Test Summary #
Tests 24/24 passing
Checks 62/62 passing
```

When I run the command `fga model test --test=.. --verbose` I get the output:
```
[
 ... JSON output ...
]
# Test Summary #
Tests 24/24 passing
Checks 62/62 passing
```

However if I make a change to a test so one test fails and run the same command `fga model test --test=.. --verbose` I get the output:
```
[
 ... JSON output ...
]
```

### Expectation

1. The test summary should not be included when using the `--verbose` flag.
2. The output should be identical in structure when using. the `--verbose` flag.

This creates problems when running the CLI tool from build scripts and I want to interpret the output.

### Reproduction

1. fga model test --test=.. --verbose
2. Check output
3. Make test fail
4. Compare output

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type organization
    relations
      define member: [user]
tuples:
  - user: user:anne
    relation: member
    object: organization:openfga
  - user: user:bob
    relation: member
    object: organization:openfga
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    check:
      - user: user:anne
        object: organization:openfga
        assertions:
          member: true
    list_objects:
      - user: user:anne
        type: organization
        assertions:
          member:
            - organization:openfga
```

### OpenFGA version

 0.4.0 (latest from homebrew)

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

Nope

### Logs

No
