### ISSUE TITLE
Multiple Parent Relation

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/openfga#1663]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

a type can have more than one parent. But defining a relationship for each parent separately makes code readability difficult.

For example,

```
type role
  relations
    define parent_role: [role]
    define parent_group: [group]
    define parent: parent_role from parent_role or parent_group from parent_group
```

Whenever I want to create a tuple, I have to check which type it is first.
According to type(parent_role, parent_group), establishing a parental relationship makes code legibility difficult, even though they are both parents.
```
writes: [
      {"user":"role:admin","relation":"parent_role","object":"role:mod"}
      {"user":"group:management","relation":"parent_group","object":"role:admin"}
  ]
```

### Describe the ideal solution

I realize that the solution below is similar to usersets, but I think the 'X from Y' logic works differently with usersets.
Thanks to the solution below, when I want to create a tuple, I only need to type parent in the relationship section.

'@' means 'X from Y'

```
type role
  relations
    define parent: [role@parent, group@parent]
```

### Alternatives and current workarounds

I don't know yet if there is a difference between usersets and parent-child, maybe the discussion here is a solution. Both syntaxes give the same result. When I define userset, a parent-child relationship is established.

https://github.com/orgs/openfga/discussions/315

**Comment by aaguiarz** [comment]
Would something like this help?

```
type user
type group
  relations
   define member : [user]
   
type role
  relations
    define parent: [role, group]
    define assignee : [user]
    define member : assignee or member from role or member from group
```

**Comment by xXAvoraXx** [comment]
> Would something like this help?
> 
> ```
> type user
> type group
>   relations
>    define member : [user]
>    
> type role
>   relations
>     define parent: [role, group]
>     define assignee : [user]
>     define member : assignee or member from role or member from group
> ```

Yes I need a solution like this, the parents of the role should have access to the role, the role can have two parents, the group and the role. But your solution gives validation error.

**Comment by aaguiarz** [comment]
Fixing it:

```
type user
type group
  relations
   define member : [user]
   
type role
  relations
    define parent: [role, group]
    define assignee : [user]
    define member : assignee or member from parent
```

**Comment by xXAvoraXx** [comment]
> Fixing it:
> 
> ```
> type user
> type group
>   relations
>    define member : [user]
>    
> type role
>   relations
>     define parent: [role, group]
>     define assignee : [user]
>     define member : assignee or member from parent
> ```

this time when I add any blocked relation in this scenario it behaves as if I added it to all of them. For example, if I block a role from a role, it is blocked from both the user and the group.

```
type user
type group
  relations
   define member : [user]
   define blocked: [user, role, group]
   
type role
  relations
    define parent: [role, group]
    define assignee : [user]
    define member : assignee or member from parent
    define blocked: [user, role, group]
```

**Comment by aaguiarz** [comment]
Can you elaborate on the blocking use case? 

Do you want to block users? role members? group members? from doing what?

**Comment by xXAvoraXx** [comment]
- Groups should be able to pass on their 'action' authorizations to their children.
- Groups should be able to pass their 'action' authorizations to their parents.

The purpose of the parent_group type is to handle the parent-child relationship. In parent_group, competencies are passed down to parents from the bottom up.

The purpose of member_group is to pass on the group's authorizations to its children.
In member_group, authorizations are passed down to children from top to bottom.

To summarize, members of a group should have access to the special permissions of that group.
There may also be a projection of authority between siblings. 

Imagine an organization chart.

The following schema passed all the tests I did based on your suggestion except the blocked relationships. The schema is working.

For example, when I want to block the access of a group's permissions(action type) to their children, when I add a tuple like below, the access of the user named 'admin' is also blocked.

why is the access of the user named 'admin' also blocked when the blocked relationship I added should only be a block between group and member_group? There is no tuple that blocks the access of 'admin'.

```
role:admin
parent
parent_group:admin

parent_group:admin
parent
parent_group:management

parent_group:management
member
group:management

member_group:management
member
group:management

**member_group:management
blocked
group:management**
```

![image](https://github.com/openfga/openfga/assets/6988989/ecd42d4b-15c2-469c-afd9-bc02d606326d)

```
type group
  relations
    define member: [parent_group, member_group]
    define blocked: [user, role#member, parent_group#member, member_group#member]
    define can_access: can_access from member but not blocked

type parent_group
  relations
    define parent: [parent_group, role]
    define sibling: [parent_group, role]
    define blocked: [user, role#member, parent_group#member]
    define member: member from parent or member from sibling
    define can_access: member but not blocked

type member_group
  relations
    define assignee: [member_group, role]
    define blocked: [user, role#member, member_group#member]
    define member: member from assignee
    define can_access: member but not blocked
    
type role
  relations
    define parent: [role, parent_group] 
    define sibling: [role, parent_group]
    define assignee: [user]
    define blocked: [user, role#member, parent_group#member]
    define member: assignee or member from parent or member from sibling
    define can_access: member but not blocked
```

**Comment by xXAvoraXx** [comment]
I guess it can't decide which one to block in multiple blocked relationships.

**Comment by xXAvoraXx** [comment]
In my tests since yesterday, if at least one of the 'blocked' relationships is blocked, it behaves as if the other paths are also blocked. Can this behavior be fixed?

I will give the same example again, imagine a river and at the end of the river there is a fork. One of the forked paths is blocked and the other is not. In this scenario, the system currently behaves as follows, when a 'check' query is executed, there are two paths to the result on the tree and one of these two paths is blocked. As a result of the query, instead of choosing the path without obstacles, it prefers the path with obstacles. In this case, unblocked users are also blocked.

**Comment by rhamzeh** [comment]
Hi @xXAvoraXx - in FGA if the user has a relation to the object through whatever, it is assumed that they have a relation. There is no way to tell FGA to require a totality or a subset of the paths.

> Imagine that there are two paths in a river and if I block one of the paths, the other is open, right

I think you are misunderstanding one thing here - namely that blocked is somehow different from other relations. `blocked` is just another relation (you can call it by another name, try allowed for example - it won't make a difference). So if the user has any open path to that blocked relation, then we consider them to have a `blocked`. (blocked is not the stones in the river, it is the end of the path).

We do not consider this a design flaw - this is how the system works.

You are asking that in this case, we consider Anne has access to group B, because although Anne has been blocked, she also has access through group A:

```yaml
model: |
  model
    schema 1.1

  type user

  type group
    relations
      define parent: [group]
      define member: [user] or member from parent
      define can_access: member but not blocked
      define blocked: [user]
tuples:
  - user: user:anne
    relation: member
    object: group:A
  - user: group:A
    relation: parent
    object: group:B
  - user: user:anne
    relation: blocked
    object: group:B
tests:
  - name: Tests
    check:
      - user: user:anne
        object: group:B
        assertions:
          can_access: true # this cannot be true, as anne is blocked
```

But this isn't how the product works or is supposed to work.

If you want what you are thinking of, you can do the following: Instead of using `but not` and `blocked`, use `and` and `allowed`, so long as any allowed path exists, the user will be allowed access.

For example, in the case below we changed it so that instead of it being allow by default and block when we see a path to blocked, we made it blocked by default and allow when you see a path to allowed:

```yaml
model: |
  model
    schema 1.1

  type user

  type group
    relations
      define parent: [group]
      define member: [user]
      define can_access: (member and allowed) or can_access from parent
      define allowed: [user]
tuples:
  - user: user:anne
    relation: member
    object: group:A
  - user: group:A
    relation: parent
    object: group:B
  - user: user:anne
    relation: allowed
    object: group:A
tests:
  - name: Tests
    check:
      - user: user:anne
        object: group:B
        assertions:
          can_access: true
```
