### ISSUE TITLE
ReadChanges return no continuation on empty changes even when continuation token is provided

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1664]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

According to OpenFGA API docs, if there are no changes after the provided continuation token, the same token will be returned in order for it to be used when new changes are recorded. If the store never had any tuples added or removed, this token will be empty.

However,  current behaviour is that if record is empty, it will not return any continuation token even if the continuation token is provided.  This is seen in [unit test](https://github.com/openfga/openfga/blob/4b47d50594b9c7e436d64cf783c0aedba30b940f/pkg/storage/test/tuples.go#L175).

### Expectation

Same continuation token should be returned if  continuation token was provided in the request.

### Reproduction

See unit test - https://github.com/openfga/openfga/blob/4b47d50594b9c7e436d64cf783c0aedba30b940f/pkg/storage/test/tuples.go#L175

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type organization
    relations
      define member: [user]
tuples:
  - user: user:anne
    relation: member
    object: organization:openfga
  - user: user:bob
    relation: member
    object: organization:openfga
tests: # remove this if not a bug in Check or ListObjects API
  - name: test-1
    check:
      - user: user:anne
        object: organization:openfga
        assertions:
          member: true
    list_objects:
      - user: user:anne
        type: organization
        assertions:
          member:
            - organization:openfga
```

### OpenFGA version

1.5.4

### How are you running OpenFGA?

As a binary

### What datastore are you using?

Postgres

### OpenFGA Flags

any
