### ISSUE TITLE
In multiple 'blocked' relationships the 'usersets' logic does not work as expected.

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/openfga#1671]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Imagine a river and we have a boat on this river, imagine that this river bifurcates towards the end of the road and splits into two. Assume that one of the paths has an obstacle and the other does not. When our boat on the river approaches this fork in the road, you would expect it to go to the road without obstacles instead of the one with obstacles, right? This is exactly what I'm trying to explain, in 'blocked' relationships, it always chooses the 'blocked' relationship in dual path situations. Whereas the other path is open and accessible from that path.

When I add the blocking relation below, members of the group:management continue to access the group even though I have blocked members of the group:management from accessing the group.

```
  - user: group:management#member
    relation: blocked
    object: group:management
```

![scheme drawio](https://github.com/openfga/openfga/assets/6988989/fa61604a-80f1-4102-b280-e7b4c01f72d4)

### Expectation

- The admin user should have access to the management group's action named 'management'.
- The president user should not be able to access the management group's action named 'management' because the members of the management group are blocked from accessing the management group.

When I use usersets, I expect the userset block of that relationship to be blocked, but it is not blocking at the moment.
When the following tuple is added, my expectation from the system is that the 'access_member' relationship returns 'false' but currently it returns 'true'.

```
  - user: group:management#member
    relation: blocked
    object: group:management
```

![image](https://github.com/openfga/openfga/assets/6988989/86c1bb21-322f-4674-aaf5-f6a83dfb72d9)

### Reproduction

-

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type group
    relations
      define assignee: [parent_group]
      define member: [role, group]
      define blocked: [user, role#access, parent_group#access, group#member, group#assignee]
      define access_member: access from member but not blocked
      define access_assigne: access from assignee but not blocked
      define access: access_member or access_assigne
      define can_access: access
  type parent_group
    relations
      define parent: [parent_group, role]
      define sibling: [parent_group, role]
      define blocked: [user, parent_group#access, role#access]
      define access: (access from parent or access from sibling) but not blocked
      define can_access: access
  type role
    relations
      define parent: [role, parent_group]
      define sibling: [role, parent_group]
      define member: [user]
      define blocked: [user, role#access, parent_group#access]
      define access: (member or access from parent or access from sibling) but not blocked
      define can_access: access
  type action
    relations
      define blocked: [user, role#access, group#access]
      define direct_access: [user, role#access, group#access]
      define access_decision: direct_access
      define can_access: access_decision but not blocked
tuples:
  - user: parent_group:admin
    relation: assignee
    object: group:admin
  - user: parent_group:admin
    relation: parent
    object: parent_group:management
  - user: group:management
    relation: member
    object: group:admin
  - user: role:admin
    relation: parent
    object: parent_group:admin
  - user: parent_group:management
    relation: assignee
    object: group:management
  - user: parent_group:management
    relation: parent
    object: role:president
  - user: role:president
    relation: member
    object: group:management
  - user: group:management#access
    relation: direct_access
    object: action:management
  - user: user:admin
    relation: member
    object: role:admin
  - user: user:president
    relation: member
    object: role:president
  - user: group:management#member
    relation: blocked
    object: group:management
tests:
  - name: Test for restricting access of management group members to the management group and its resources.
    check:
      - user: user:admin
        object: action:management
        assertions:
          can_access: true
      - user: user:president
        object: action:management
        assertions:
          can_access: false
```

### OpenFGA version

openfga/cli#v0.4.1

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

none

**Comment by xXAvoraXx** [comment]
### Scenario 2

This scenario contains schemas and tuples that illustrate the river scenario I described above.

### Description




When I add the blocking relation below, members of the group:management continue to access the group even though I have blocked members of the group:management from accessing the group.

```
  - user: member_group:management#access
    relation: blocked
    object: group:management
```


![Scenario2 drawio](https://github.com/openfga/openfga/assets/6988989/a43d1350-6130-46d0-89f8-38d298b8f5bc)


### Expectation

- The admin user should have access to the management group's action named 'management'.
- The president user should not be able to access the management group's action named 'management' because the members of the management group are blocked from accessing the management group.

In this scenario there is a blocking relationship between member_group and group, remember the river scenario, user 'Admin' has two alternative paths to access action:management, one of these paths is blocked and the other is open, the problem is why is it choosing the blocked path instead of choosing the open path? User 'Admin' should be able to access action:management but cannot.

```
  - user: member_group:management#access
    relation: blocked
    object: group:management
```


![image](https://github.com/openfga/openfga/assets/6988989/5c3e8422-24c9-45cf-aaaa-55f9d807bd59)


### Reproduction

-

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
  type group
    relations
      define assignee: [parent_group, member_group]
      define blocked: [user, role#access, parent_group#access, member_group#access]
      define access: access from assignee but not blocked
      define can_access: access
  type parent_group
    relations
      define parent: [parent_group, role]
      define sibling: [parent_group, role]
      define blocked: [user, parent_group#access, role#access]
      define access: (access from parent or access from sibling) but not blocked
      define can_access: access
  type member_group
    relations
      define member: [member_group, role]
      define blocked: [user, role#access, member_group#access]
      define access: access from member but not blocked
      define can_access: access
  type role
    relations
      define parent: [role, parent_group]
      define sibling: [role, parent_group]
      define member: [user]
      define blocked: [user, role#access, parent_group#access]
      define access: (member or access from parent or access from sibling) but not blocked
      define can_access: access
  type action
    relations
      define blocked: [user, role#access, group#access]
      define direct_access: [user, role#access, group#access]
      define access_decision: direct_access
      define can_access: access_decision but not blocked
tuples:
  - user: parent_group:admin
    relation: assignee
    object: group:admin
  - user: member_group:admin
    relation: assignee
    object: group:admin
  - user: parent_group:admin
    relation: parent
    object: parent_group:management
  - user: member_group:management
    relation: member
    object: member_group:admin
  - user: role:admin
    relation: parent
    object: parent_group:admin
  - user: parent_group:management
    relation: assignee
    object: group:management
  - user: member_group:management
    relation: assignee
    object: group:management
  - user: parent_group:management
    relation: parent
    object: role:president
  - user: role:president
    relation: member
    object: member_group:management
  - user: group:management#access
    relation: direct_access
    object: action:management
  - user: user:admin
    relation: member
    object: role:admin
  - user: user:president
    relation: member
    object: role:president
  - user: member_group:management#access
    relation: blocked
    object: group:management
tests:
  - name: Test for restricting access of management group members to the management group and its resources.
    check:
      - user: user:admin
        object: action:management
        assertions:
          can_access: true
      - user: user:president
        object: action:management
        assertions:
          can_access: false
```


### OpenFGA version

openfga/cli#v0.4.1

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

**Comment by xXAvoraXx** [comment]
### Scenario 3

In the third scenario, the 'blocked' relations work as expected, but as the tuples increase, it gives the following error, this error can be solved by increasing resolveNodeLimit but I don't know if this is a solution.

> Authorization Model resolution required too many rewrite rules to be resolved. Check your authorization model for infinite recursion or too much nesting

### Description


When I add the blocking relation below, After adding a blocking relationship between member_group and group, the members of 'member_group' are blocked from accessing group:management, but the admin user is also blocked.

I think the 'blocked' relationship is blocked because the user 'admin' is indirectly a member of member_group, but the same user 'admin' is indirectly the parent of parent_group:management, so it needs to access group:management indirectly. The syntax 'but not' seems to skip indirect paths when choosing the blocking relation. I think this is a bug.

```
  - user: member_group:management#access
    relation: blocked
    object: group:management
```


![TEST drawio](https://github.com/openfga/openfga/assets/6988989/b55a9a04-9d7a-44fd-8fad-ef86802493e5)



### Expectation

This scenario works as expected until the tuples reach a certain size.

- The admin user should have access to the management group's action named 'management'.
- The president user should not be able to access the management group's action named 'management' because the members of the management group are blocked from accessing the management group.

> Authorization Model resolution required too many rewrite rules to be resolved. Check your authorization model for infinite recursion or too much nesting


### Reproduction

-

### Store data

```yaml
model_file: |
  model
    schema 1.1
  type user
type group
  relations
    define member: [parent_group#access, member_group#access]
    define blocked: [user, role#access, parent_group#access, member_group#access]
    define access: member but not blocked
    define can_access: access
type parent_group
  relations
    define parent: [parent_group#access, role#access] but not blocked
    define sibling: [parent_group#access, role#access] but not blocked
    define blocked: [user, parent_group#access, role#access]
    define access: parent or sibling
    define can_access: access
type member_group
  relations
    define member: [member_group#member, role#member]
    define blocked: [user, role#access, member_group#member]
    define access: member but not blocked
    define can_access: access
type role
  relations
    define parent: [role#access, parent_group#access]
    define sibling: [role#access, parent_group#access]
    define member: [user] or parent or sibling
    define blocked: [user, role#access, parent_group#access]
    define access: member but not blocked
    define can_access: access
  type action
    relations
      define blocked: [user, role#access, group#access]
      define direct_access: [user, role#access, group#access]
      define access_decision: direct_access
      define can_access: access_decision but not blocked
tuples:
  - user: parent_group:admin#access
    relation: member
    object: group:admin
  - user: member_group:admin#access
    relation: member
    object: group:admin
  - user: parent_group:admin#access
    relation: parent
    object: parent_group:management
  - user: member_group:management#member
    relation: member
    object: member_group:admin
  - user: role:admin#access
    relation: parent
    object: parent_group:admin
  - user: parent_group:management#access
    relation: member
    object: group:management
  - user: member_group:management#access
    relation: member
    object: group:management
  - user: parent_group:management#access
    relation: parent
    object: role:president
  - user: role:president#member
    relation: member
    object: member_group:management
  - user: group:management#access
    relation: direct_access
    object: action:management
  - user: user:admin
    relation: member
    object: role:admin
  - user: user:president
    relation: member
    object: role:president
  - user: member_group:management#access
    relation: blocked
    object: group:management
tests:
  - name: Test for restricting access of management group members to the management group and its resources.
    check:
      - user: user:admin
        object: action:management
        assertions:
          can_access: true
      - user: user:president
        object: action:management
        assertions:
          can_access: false
```


### OpenFGA version

openfga/cli#v0.4.1

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory
