### ISSUE TITLE
"Internal Server Error" on Check and ListUsers

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1766]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Both of the requests below throw a 500: `folder1#viewer relation is undefined`

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/868bea6d-df0d-468b-ae48-4f085e9e4469">

### Expectation

Check should return allowed=false and ListUsers should return an empty array

### Reproduction

See below

### Store data

```
name: Test

model: |+
    model
      schema 1.1

    type user
    type folder1
    type folder2
      relations
        define viewer: [user]
    type doc
      relations
        define viewer: viewer from parent
        define parent: [folder1, folder2]

tuples:
  - user: folder1:x
    relation: parent
    object: doc:x
tests:
  - name: internal-server-error
    check:
      - user: user:maria
        object: doc:x
        assertions:
          viewer: false
    list_users:
      - object: doc:x
        user_filter:
          - type: user
        assertions:
          viewer:
```

### OpenFGA version

Commit 518606928ded775a86a6ed69c4e6faa245e9b372

### How are you running OpenFGA?

As a binary

### What datastore are you using?

Postgres

### OpenFGA Flags

no
