### ISSUE TITLE
Userset relationships not working correctly

### ISSUE THREAD

**Issue by sidneibjunior** [openfga/openfga#1828]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Userset relation is not working correctly on latest openfga version.

I have the following model where the permission to access a job is granted thought this path `user > role > permission > job`.
The attached store data works on openfga `v1.5.6`, but stopped working on `v1.5.7` and `v.1.5.8`.

### Expectation

User object should have access to job.

### Reproduction

Open the following fga playground and run the tests: https://play.fga.dev/stores/create/?id=01J4VF05ZY709AP9HMDP195RDE

### Store data

```yaml
model_file: |
  name: fga-bug
description: 'Store ID: 01J4VF05ZY709AP9HMDP195RDE'
model: |
  model
    schema 1.1

  type user

  type role
    relations
      define assignee: [user]

  type permission
    relations
      define assignee: assignee from role
      define role: [role]

  type job
    relations
      define can_read: [permission#assignee]
tuples:
  - user: user:1
    relation: assignee
    object: role:admin
  - object: permission:readJobs
    user: role:admin
    relation: role
  - object: job:1
    user: permission:readJobs#assignee
    relation: can_read
tests:
  - name: Tests
    check:
      - user: user:1
        object: job:1
        assertions:
          can_read: true
```

### OpenFGA version

v.1.58

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

No specific flags
