### ISSUE TITLE
Evaluate all tuples if requested when evaluating a relation

### ISSUE THREAD

**Issue by geoffroybraun** [openfga/openfga#2156]
### Checklist

- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

Hi all,

recently, we faced a new behavior regarding authorizations and it caught us off guard. One of our business need is to evaluate all tuples when checking a relation. Instead of returning `true` as soon as a relation is valid, we would like to crawl all relations available before taking a decision.

### Describe the ideal solution

An ideal solution would be to indicate within the authorization model which relation requires all tuples to be evaluated. Here is an example  where users read / write / administrate files and files belong to folders.

```yaml
type user

type document
  relations
    define reader: [user]
    define writer: [user]
    define owner: [user]
    define can_read: reader or writer or administrator
    define can_write: writer or administrator
    define can_administrate: owner

type folder
  relations
    define belong_to: [document]
    define owner: [user]
    define can_administrate: owner or can_administrate from belong_to{all}
```

In the authorization model above, the `user` type can administrate a folder if it can administrate all files belonging to the same folder. The instruction `{all}` after the `belong_to` relation indicates that all relations must be evaluated and true ir order to consider the relation as available if the user does not own the folder but he/she can administrate all contained files.

> Note: we are aware this might have an impact on global performances.

### Alternatives and current workarounds

So far, this kind of authorizations is performed by the application itself, where we get the list of files belonging to a folder and we evaluate the `can_administrate` relation between the user and each file. We keep evaluating until the end of the file list is reached or as far as the user does not have the relation with a file. It would be easier and faster for us to perform this evaluation within OpenFga graph.

### Additional context

As usual, please let me know if you need further information or would like to discuss it live.

Cheers,
