### ISSUE TITLE
"[...] relation is referenced in at least one tupleset and thus must be a direct relation" and we don't get why

### ISSUE THREAD

**Issue by geoffroybraun** [openfga/openfga#2205]
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Hi there,

recently, we faced an issue we are not able to fix. As usual, here is an example with simplified business rules to understand the problem:
* an entity belongs to a `parent` organization.
* an organization has `children` entities.
* entities can have a `subscription`.
* custom features can be enabled on entities.
* if an entity has custom features enabled and a subscription, then the parent organization also has access to the custom features.

Of course, these are not our current business rules, we simplified them, the point still is the same: if a child has access to something, we want to transmit it to its parent. Here is the model and tests we use for this example (keep in mind that types and relations are modelized that way because this is exactly what we want from a business point of view).

```yaml
---
name: tests

model: |
  model
    schema 1.2
  type user
  type entity
    relations
      define parent: [organization]
      define subscription: [entity]
      define custom_features: [entity]
      define has_custom_features_enabled: custom_features and subscription
      define has_organization_custom_features_enabled: parent from has_custom_features_enabled
  type organization
    relations
      define children: [file]
      define has_custom_features_enabled: has_organization_custom_features_enabled from children

tuples:
  - user: entity:a
    relation: children
    object: organization:a
  - user: organization:a
    relation: parent
    object: entity:a
tests:
  - name: Custom features enabled on an entity are also enabled on the parent organization
    description: Ensure custom features are transmitted to an entity parent organization when enabled
    tuples:
      - user: entity:a
        relation: enable_custom_features
        object: entity:a
    check:
      - user: organization:a
        object: organization:a
        assertions:
          has_custom_features_enabled: true
  - name: Custom features disabled on an entity are also disabled on the parent organization
    description: Ensure custom features are not transmitted to an entity parent organization when disabled
    check:
      - user: organization:a
        object: organization:a
        assertions:
          has_custom_features_enabled: false
```

As explained in the title, when running the command `fga model test --tests my-test-file.fga.yaml` using the CLI, we receive the following log error:

> Error: error running tests due to rpc error: code = Code(2056) desc = the 'entity#has_custom_features_enabled' relation is referenced in at least one tupleset and thus must be a direct relation

We don't understand why the `has_custom_features_enabled` relation on the `file` type is considered as a _tupleset_ one, we simply want to redirect to the entity itself if custom features are enabled. We discussed this _trick_ with @aaguiarz months ago and we are actively using it, it's perfectly working. The difference with this current example is that we move from a type to another, and this seems to break the model.

I saw issue openfga/openfga#2137 while searching for the error message but that is all I found. Please let me know why we can't have concentric relation pointing to concentric relation.

Cheers,

Geoffroy

### OpenFGA version

1.8.3

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

no
