### ISSUE TITLE
Add a test to make sure `Dockerfile.goreleaser` builds correctly

### ISSUE THREAD

**Issue by rhamzeh** [openfga/openfga#2285]
### Checklist

- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

If we do any mistake while updating [Dockerfile.goreleaser](https://github.com/openfga/openfga/blob/main/Dockerfile.goreleaser) - we won't know until the time for releasing if anything breaks - like what happened here: https://github.com/openfga/openfga/actions/runs/13415364168

### Describe the ideal solution

Add the following to the workflow testing PRs going to main

https://github.com/openfga/cli/blob/main/.github/workflows/main.yaml#L116-L121

```yaml
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean --config .goreleaser.yaml --snapshot --skip sign,publish,announce
```

What this does is ensure that goreleaser can build - but skips signing, publishing and announcing
