### ISSUE TITLE
Getting deadline_exceeded response and running out of db conns

### ISSUE THREAD

**Issue by frisket** [openfga/openfga#2422]
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

We've run into a problem where all fga requests fail with deadline_exceeded error response, including even the health check!

We've done some experimentation and we've found the folllowing:

- When this happens the database connections are consumed up to the max-pool size via OPENFGA_DATASTORE_MAX_OPEN_CONNS (in our case, the default 30)
- The db conns never shrink back to the min 10 (OPENFGA_DATASTORE_MAX_IDLE_CONNS) even when idle
- Versions up to 1.8.6 work correctly
- Version 1.8.7 and higher all fail basically immediately within a small number of check requests - 30-40
- On versions up to 1.8.6 the db connections are all cleared/freed up and go back to the min (10) as expected after the requests
- Once it reaches this state the service is broken and no further requests are handled.  Only a restart will fix it.

The actual response we get for every API request after this happens is:

```
{"code":"deadline_exceeded","message":"Request Deadline Exceeded"}
```

We don't have many tuples - only ~35k and the model is relatively simple.  I don't believe it is model or data related as everything works unchanged up to version 1.8.6 without issue.

Not sure where to go from here as the 1.8.7 changelogs don't really give any clues and the git diffs aren't too enlightening for me as I'm not familiar with the code base.

We've tried enabling additional logging with '--log-level=debug' but that doesn't seem to provide any data or any additional data at all.

Any suggestions or pointers to resolving this issue would be appreciated.  For now we're sticking with 1.8.6. as it works.

### OpenFGA version

1.8.7->1.8.11

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

OPENFGA_LOG_FORMAT=json OPENFGA_LOG_LEVEL=debug

**Comment by adriantam** [comment]
Can you share what is the configuration on your system?  More specifically, the number of DB connections as well as whether any optimization flag is enabled?

**Comment by frisket** [comment]
Certainly.  It's a fairly test system, nothing special:

- Debian 12.8 (uname output: `Linux apptest 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux`)
- Postgres 15.9
- max_connections=500

Note that it's openfga running out of DB connections, not the database.  The database continues to run just fine and respond normally when openfga gets stuck.

Configuration wise, it's basically stock/defaults except for the ones noted to enable json logging and debug logs.

It's quite reproduceable as well - it's happened on 3 separate test instances already with similarly basic configuration.

Here's the docker compose we're using:

```
  openfga:
    depends_on:
      - openfga-migrate
    image: openfga/openfga:v1.8.11
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: run
    ports:
      - "48080:8080"
      - "48081:8081"
      - "13000:3000"
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@${DB_ADDRESS}:5432/openfga
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_PLAYGROUND_PORT=13000
      - OPENFGA_LOG_LEVEL=debug

```

Our next steps will be to try playing with the model/tuples and see if that makes any difference.
