### ISSUE TITLE
OpenFGA Check returns erroneous results with contextual Tuples

### ISSUE THREAD

**Issue by udyvish** [openfga/openfga#2466]
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Below is my OpenFGA authorisation model:
```
model
  schema 1.1

type user

type group
  relations
    define member: [user]

type region
  relations
    define member: [user:*, group#member]

type role
  relations
    define assignee: [user]

type security_group
  relations
    define assignee: [user:*, group#member]

type deployment
  relations
    define region: [region]
    define security_group: [security_group]
    define can_access: [user:*, role#assignee] or (assignee from security_group and member from region)
```

I am running OpenFGA in a container using docker-compose.
```yaml
  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
```

I am running below checks:

```go
package main

import (
	"context"
	"fmt"
	"log"

	openfga "github.com/openfga/go-sdk/client"
)

func main() {
	storeId := "01JVVQQ5TAJ04EY8NP2AMRCHPR"
	authId := "01JVVQQ5TVRDKZF30SVZZ4V517"

	client, err := openfga.NewSdkClient(&openfga.ClientConfiguration{
		ApiUrl:               "http://127.0.0.1:8080",
		StoreId:              storeId,
		AuthorizationModelId: authId,
	})
	if err != nil {
		log.Fatal(err)
	}

	_, err = client.WriteTuples(context.Background()).Body(openfga.ClientWriteTuplesBody{
		{
			User:     "role:superadmin#assignee",
			Relation: "can_access",
			Object:   "deployment:deployment_1",
		},
	}).Execute()
	if err != nil {
		log.Fatal(err)
	}

	res, err := client.Check(context.Background()).Body(openfga.ClientCheckRequest{
		User:     "user:jdoe",
		Relation: "can_access",
		Object:   "deployment:deployment_1",
	}).Execute()

	if err != nil {
		log.Fatal(err)
	}

	// allowed=false
	// user:jdoe should not be allowed to access india_deployment_1
	fmt.Println(res.GetAllowed())

	res, err = client.Check(context.Background()).Body(openfga.ClientCheckRequest{
		User:     "user:jdoe",
		Relation: "can_access",
		Object:   "deployment:deployment_1",
		ContextualTuples: []openfga.ClientContextualTupleKey{
			{
				User:     "role:superadmin#assignee",
				Relation: "can_access",
				Object:   "deployment:deployment_1",
			},
		},
	}).Execute()

	if err != nil {
		log.Fatal(err)
	}

	// allowed=true
	// Error: user:jdoe should not be allowed to access deployment_1 since they are not assigned role:superadmin
	fmt.Println(res.GetAllowed())
}
```

I expect both cases to return `allowed: false` since `user:jdoe` is not assigned `role:superadmin`. But in the first case, OpenFGA returns `allowed: false` when the Tuple is already written, whereas in the second case, it returns `allowed: true` where Tuples are sent as contextual tuples.

### OpenFGA version

OpenFGA version `v1.8.12` build from `5f720784ae7c637bc9a9ae8a18adc230982aba50`

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

just env vars in docker compose mentioned above
