### ISSUE TITLE
ci: add `.goreleaser-nightly.yaml` manifest for nightly releases

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#76]
It would be nice to get nightly releases of the `main` branch so that each new day a developer can run the latest software on the `main` branch. We should add a `.goreleaser-nightly.yaml` manifest specifically for nightly releases.

Design goals:
* A nightly release should only build and publish a new container image (e.g. `openfga/openfga:nightly`). No Github releases, Homebrew packages, etc..
* Nightly releases should not override the `openfga/openfga:latest` image, because the latest image tag should always point to the latest "tagged" release.

We need to also make sure we add documentation to the README that indicates you can use nightly builds to test out new functionality on main. An example Github action workflow would look like:

```yaml
name: Nightly Release
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser-nightly.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
