### ISSUE TITLE
Adding support for AWS IAM Authentication

### ISSUE THREAD

**Issue by KlausVii** [openfga/openfga#870]
Hi folks,

We recently deployed openfga on our cluster and we ran into some friction with having to be forced to use user+password auth for our postgres, as all our other services use IAM auth for our db access everywhere else.

Would you be happy add this support? If so, we would be happy sort out the PR.

Many thanks :)

**Comment by rhamzeh** [comment]
Hi @KlausVii - absolutely, we'd love a contribution!

**Comment by KlausVii** [comment]
@rhamzeh - Lovely.

Here's the preliminary flag changes I think we'll need:
- datastore-use-aws-iam: boolean

And probably to decompose the db uri into these to make the setup a bit easier
- datastore-db-name: string
- datastore-db-port: string
- datastore-db-host: string

Are we happy to leave the AWS_ vars to be passed as is and not included the in flags? Or should there be an option to pass them explicitly?

Let me know what you think. I should be able to get started on this later this week.

**Comment by rhamzeh** [comment]
cc @jon-whit : I think you have the most comments/thoughts on this

**Comment by jon-whit** [comment]
@KlausVii could we open this up for a larger discussion in a more formal RFC (see https://github.com/openfga/rfcs)?

What I'd like to see, beyond just a rough cut of immediately supporting AWS IAM credentials for database credentials, is a rough plan of what this looks like as a developer (what's the setup and DX for this new credential management process) and what _may_ it look like for the other vendors out there (Azure, GCP, etc..). Some open questions:

* **Package structure** - We're introducing a new auth method for the storage layer, and this is potentially for more than one vendor. I'd like to see a recommendation/proposal for that.

* **Config structure** - We support config.yaml, env vars, and flags. Each of these need a proposed change associated with them, and the config structure will vary based on the auth provider I'm sure. We can focus on AWS, but we should at least have a rough story for one other vendor.

* **Interface composition** - At the end of the day the abstraction is a database/sql connection pool to the underlying SQL database through a driver (e.g. `pgx` for postgres or `go-sql-driver/mysql`), but how you obtain that is changing. I'd like to see an attempt for a proposal for an interface that is shared across the implementations that abstracts away the connection details and has implementations specific to the providers. The [Go Cloud CDK](https://gocloud.dev/howto/sql/) might be a good starting point for inspiration or maybe we just adopt that altogether as the defacto standard for our implementation?

    For example:
    * [AWS IAM authentication (v2) to Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.Go.html#UsingWithRDS.IAMDBAuth.Connecting.GoV2) you use the AWS credentials (which is a proprietary spec for storing and managing creds on the filesystem), obtain an access token, and then construct the connection uri. 

     * [GCP Cloud SQL](https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-databasesql-connect-connector) the app uses the GCP app default credentials (similar to AWS credentials), obtain an authenticated connection via a cloudsql dialer, and then uses that along with the driver.

Even if the RFC is merely an open conversation between just us, then at least the community can reflect back on the decision via a more formal document.

**Comment by KlausVii** [comment]
@jon-whit Sounds reasonable, I'll try and scrape something together.

**Comment by KlausVii** [comment]
Sorry it took a while, but I've opened an RFC now, please let me know what thoughts you may have.

**Comment by KlausVii** [comment]
@jon-whit has there been any movement on this? I'd still be happy finish the implementation if openfga is likely accept it

**Comment by maxswjeon** [comment]
Looking for IAM Authentication support too, but a little bit worried that this issue is stale.

**Comment by ChrisJBurns** [comment]
@KlausVii @maxswjeon  You can actually do this without having to have the OpenFGA application natively support it. If you run the `aws rds generate-db-auth-token` command in a sidecar/init container ensuring to output the contents to a `.pgpass` file that is mounted into the main `openfga` container. As long as your URI doesn't contain the password, the underlying [`lib/pq`](https://github.com/lib/pq)that most Go libraries use will actually look to the place thats configured by the `PGPASSFILE` env var. Just point the envvar at the place you mount the `.pgpass` file and the `openfga` container should be able to connect. I know this because we ourselves have done it. It would be nice for the `openfga` app to support it natively, but in the time that it doesn't, you can use the above as a way around it.

If you're installing with the [OpenFGA Helm Chart](https://github.com/openfga/helm-charts), you'll run into the problem of initContainer vs jobs, which is why I've raised https://github.com/openfga/helm-charts/issues/191. 

But having tested it myself, I can verify it works and the pods start and connect to the database using the new RDS IAM user.

**Comment by rhyas** [comment]
I don't know if anyone else has tried to get this working, but even if you get the initContainer working for the migrate job, it looks like the migrate job uses a different database init procedure and has a bug. It [sets an empty password](https://github.com/openfga/openfga/blob/ee82979118d34fc75c6a5e8c02173a7ac7f90f43/cmd/migrate/migrate.go#L107) in the URI, which seems to not let the driver fall back to DBPASSFILE, causing it to try to connect with an empty password, and fail, even if the token is set through the env/file correctly. This means the Helm Chart, even with the fixes in https://github.com/openfga/helm-charts/issues/191 (Thanks for raising that @ChrisJBurns ) still won't actually work like it should with the init container.

If anyone else has gotten the migrate job to work with IAM, I'd love to hear how.  (:

**Comment by JeremyLoy** [comment]
hey @ChrisJBurns - thanks for your comment, I'm also attempting to get OpenFGA running in ECS + RDS + with IAM Authentication.

I'm curious - how are you dealing with the auth-token expiration? (currently seems to be 15 minutes) 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html

**Comment by ChrisJBurns** [comment]
@JeremyLoy  Hey bud, yeh so we have a sidecar container that basically queries the generate token endpoint and mounts it as password in the .pgpass file on the main OpenFGA pod. We then tell OpenFGA container to use the PGPASSFILE as OpenFGA is using `lib/pq` under the hood.

```yaml
        sidecars:
          - name: aws-dynamic-rds-password
            image: public.ecr.aws/aws-cli/aws-cli@sha256:07cc353f732a986c45ee0a8082c56442ade50b114f668df6af97b1b156916e5a # 2.15.7
            command: ["/bin/bash"]
            args:
              - "-c"
              - |
                while true; do
                  (echo -n "*:*:*:*:"; aws rds generate-db-auth-token --hostname $DBHOST --port 5432 --username OPENFGA_USERNAME | sed 's|:|\\:|g') > /secrets/db/.pgpass && chmod 600 /secrets/db/.pgpass
                  sleep 600  # STS tokens are good for 15 minutes
                done
            env:
              - name: "DBHOST"
                value: [RDS_URL]
              # AWS volume was built to run as root, see
              # https://github.com/aws/aws-cli/issues/5120#issuecomment-1473860012
              - name: HOME
                value: "/tmp"
            securityContext:
              runAsUser: 65532 # Same as 'ko'
            volumeMounts:
              - name: db-password
                mountPath: /secrets/db
```

We then provide a env var to tell openfga to look for the password in the PGPASSFILE
```yaml
       - name: PGPASSFILE
          value: /secrets/db/.pgpass
```

Hope this helps.
