### ISSUE TITLE
Support Contextual Tuples in Assertions API

### ISSUE THREAD

**Issue by lorenlew** [openfga/openfga#946]
Would it possible for the assertions to take into consideration the contextual tuples? (for advanced scenarios with contextual based access)
For now the assertions are pure (object, relation, subject) tuples.

**Comment by rhamzeh** [comment]
Hi @lorenlew - right now it doesn't however we are planning an overhaul of that API.

The new interface will be coming to the CLI first so that we can get all your feedback on it before adding support for it to the API itself.

You can see @aaguiarz talk about it in our latest community meeting: https://youtu.be/6oQOKgJ53V0?t=1602

It is expected to look something like this, where each test can have its own contextual tuples:
```yaml
tests:
  - name: folder-access
    description: ""
    tuples:
      - user: user:anne
        relation: owner
        object: folder:product
      - user: folder:product
        relation: parent
        object: folder:product-2021
      - user: user:beth
        relation: viewer
        object: folder:product-2021
    check:
      - user: user:anne
        object: folder:product-2021
        assertions:
          can_view: true
          can_write: true
          can_share: true
      - user: user:beth
        object: folder:product-2021
        assertions:
          can_view: true
          can_write: false
          can_share: false
    list-objects:
      - user: user:anne
        type: folder
        assertions:
          can_view:
            - folder:product
            - folder:product-2021
          can_write:
            - folder:product
            - folder:product-2021
          can_share:
            - folder:product
            - folder:product-2021
      - user: user:beth
        type: folder
        assertions:
          can_view:
            - folder:product-2021
          can_write: []
          can_share: []
```

Let us know what you think!
